# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ml_pb2 as ml__pb2


class MLStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateDocument = channel.unary_unary(
                '/model.ML/GenerateDocument',
                request_serializer=ml__pb2.DocumentRequest.SerializeToString,
                response_deserializer=ml__pb2.DocumentResponse.FromString,
                )
        self.GenerateCommit = channel.unary_unary(
                '/model.ML/GenerateCommit',
                request_serializer=ml__pb2.CommitRequest.SerializeToString,
                response_deserializer=ml__pb2.CommitResponse.FromString,
                )


class MLServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateCommit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MLServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateDocument,
                    request_deserializer=ml__pb2.DocumentRequest.FromString,
                    response_serializer=ml__pb2.DocumentResponse.SerializeToString,
            ),
            'GenerateCommit': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateCommit,
                    request_deserializer=ml__pb2.CommitRequest.FromString,
                    response_serializer=ml__pb2.CommitResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'model.ML', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ML(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/model.ML/GenerateDocument',
            ml__pb2.DocumentRequest.SerializeToString,
            ml__pb2.DocumentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenerateCommit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/model.ML/GenerateCommit',
            ml__pb2.CommitRequest.SerializeToString,
            ml__pb2.CommitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
