# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ml.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08ml.proto\x12\x05model\"G\n\x0f\x44ocumentRequest\x12\x10\n\x08language\x18\x01 \x01(\t\x12\x14\n\x0cnum_response\x18\x02 \x01(\x05\x12\x0c\n\x04\x63ode\x18\x03 \x01(\t\"\x1f\n\x10\x44ocumentResponse\x12\x0b\n\x03\x64oc\x18\x01 \x03(\t\"9\n\rCommitRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x14\n\x0cnum_response\x18\x02 \x01(\x05\"%\n\x0e\x43ommitResponse\x12\x13\n\x0b\x63ommit_msgs\x18\x01 \x03(\t2\x8c\x01\n\x02ML\x12\x45\n\x10GenerateDocument\x12\x16.model.DocumentRequest\x1a\x17.model.DocumentResponse\"\x00\x12?\n\x0eGenerateCommit\x12\x14.model.CommitRequest\x1a\x15.model.CommitResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_DOCUMENTREQUEST']._serialized_start=19
  _globals['_DOCUMENTREQUEST']._serialized_end=90
  _globals['_DOCUMENTRESPONSE']._serialized_start=92
  _globals['_DOCUMENTRESPONSE']._serialized_end=123
  _globals['_COMMITREQUEST']._serialized_start=125
  _globals['_COMMITREQUEST']._serialized_end=182
  _globals['_COMMITRESPONSE']._serialized_start=184
  _globals['_COMMITRESPONSE']._serialized_end=221
  _globals['_ML']._serialized_start=224
  _globals['_ML']._serialized_end=364
# @@protoc_insertion_point(module_scope)
