# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: editor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x65\x64itor.proto\x12\x06\x65\x64itor\"\x1a\n\nAPMRequest\x12\x0c\n\x04time\x18\x01 \x01(\x03\"\x1a\n\x0b\x41PMResponse\x12\x0b\n\x03\x61pm\x18\x01 \x01(\x02\x32=\n\x06\x45\x64itor\x12\x33\n\x06GetAPM\x12\x12.editor.APMRequest\x1a\x13.editor.APMResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'editor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_APMREQUEST']._serialized_start=24
  _globals['_APMREQUEST']._serialized_end=50
  _globals['_APMRESPONSE']._serialized_start=52
  _globals['_APMRESPONSE']._serialized_end=78
  _globals['_EDITOR']._serialized_start=80
  _globals['_EDITOR']._serialized_end=141
# @@protoc_insertion_point(module_scope)
