# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import editor_pb2 as editor__pb2


class EditorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAPM = channel.unary_unary(
                '/editor.Editor/GetAPM',
                request_serializer=editor__pb2.APMRequest.SerializeToString,
                response_deserializer=editor__pb2.APMResponse.FromString,
                )


class EditorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAPM(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EditorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAPM': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAPM,
                    request_deserializer=editor__pb2.APMRequest.FromString,
                    response_serializer=editor__pb2.APMResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'editor.Editor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Editor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAPM(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/editor.Editor/GetAPM',
            editor__pb2.APMRequest.SerializeToString,
            editor__pb2.APMResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
