# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ml.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08ml.proto\x12\x05model\"B\n\x04\x43ode\x12\x10\n\x08language\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\r\n\x05start\x18\x03 \x01(\x05\x12\x0b\n\x03\x65nd\x18\x04 \x01(\x05\"4\n\x0bInstruction\x12\x10\n\x08language\x18\x01 \x01(\t\x12\x13\n\x0binstruction\x18\x02 \x01(\t\"%\n\x0e\x43odeCompletion\x12\x13\n\x0b\x63ompletions\x18\x01 \x03(\t\")\n\x0eImplementation\x12\x17\n\x0fimplementations\x18\x01 \x03(\t\"\x1b\n\x07\x45xample\x12\x10\n\x08\x65xamples\x18\x01 \x03(\t\"\x1a\n\x07\x43omment\x12\x0f\n\x07\x63omment\x18\x01 \x01(\t2\xa0\x02\n\x02ML\x12\x39\n\x11GetCodeCompletion\x12\x0b.model.Code\x1a\x15.model.CodeCompletion\"\x00\x12\x30\n\x0fGenerateComment\x12\x0b.model.Code\x1a\x0e.model.Comment\"\x00\x12\x45\n\x16GenerateImplementation\x12\x12.model.Instruction\x1a\x15.model.Implementation\"\x00\x12\x34\n\x0cGenerateTest\x12\x0b.model.Code\x1a\x15.model.Implementation\"\x00\x12\x30\n\x0fGenerateExample\x12\x0b.model.Code\x1a\x0e.model.Example\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CODE']._serialized_start=19
  _globals['_CODE']._serialized_end=85
  _globals['_INSTRUCTION']._serialized_start=87
  _globals['_INSTRUCTION']._serialized_end=139
  _globals['_CODECOMPLETION']._serialized_start=141
  _globals['_CODECOMPLETION']._serialized_end=178
  _globals['_IMPLEMENTATION']._serialized_start=180
  _globals['_IMPLEMENTATION']._serialized_end=221
  _globals['_EXAMPLE']._serialized_start=223
  _globals['_EXAMPLE']._serialized_end=250
  _globals['_COMMENT']._serialized_start=252
  _globals['_COMMENT']._serialized_end=278
  _globals['_ML']._serialized_start=281
  _globals['_ML']._serialized_end=569
# @@protoc_insertion_point(module_scope)
